### PR TITLE
Change menu align

### PR DESCRIPTION
**Pull request by userMacieG**
Change menu align from `top-left` into `bottom-right`

### CODE REVIEW

**Comment by Tinky124** [comment]
why?????????

**Comment by Tinky124** [comment]
@userMacieG better right only..

**Comment by HumanTree92** [comment]
Honestly do a Config.MenuAlign. I have done it to every script.

**Comment by itschip** [comment]
Does not seem like an bug or error that has been fixed, nor something super important. Closing this for now.

**Pull request closed without merging**
